- hosts: localhost
  connection: local

  tasks:
  - name: Create & Start Container
    docker_container:
      name: myweb
      image: "docker.io/zackpark/hello-world:{{ lookup('env', 'BUILD_NUMBER') }}"
      state: started
      ports:
      - "80:8080"
